name: Automated Testing CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: 3.12

    - name: Install build dependencies
      run: |
        python -m ensurepip --upgrade
        pip install --upgrade pip setuptools wheel

    - name: Install project dependencies
      run: |
        pip install -r project/requirements.txt

    - name: Run tests.sh
      run: |
        chmod +x project/tests.sh
        project/tests.sh
